# Site settings
title: 'Todd Motto'
email: todd@toddmotto.com
description: > # this means to ignore newlines until "baseurl:"
  Articles on JavaScript, Angular, React and HTML5
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://toddmotto.com" # the base hostname & protocol for your site
twitter_username: toddmotto
github_username:  toddmotto
paginate: 10
paginate_path: "/page:num/"
permalink: /:year/:month/:title
sass:
  compressed: true

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
